services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: ephemeral-environments-ts
    hostname: ephemeral-environments
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_KEY}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_SERVE_CONFIG=/config/tailscale-proxy.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/config:/config
      - ephemeral-environments-ts-state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    networks:
      - ephemeral-environments-network

  mysql:
    image: mysql:8.0
    container_name: ephemeral-environments-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-ephemeral_environments}
      - MYSQL_USER=${MYSQL_USER:-prenvuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-prenvpassword}
    volumes:
      - ephemeral-environments-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ephemeral-environments-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD:-rootpassword}"]
      interval: 10s
      timeout: 5s
      retries: 5

  ephemeral-environments-api:
    build:
      context: ./ephemeral-environments-api
      dockerfile: Dockerfile
    container_name: ephemeral-environments-api
    restart: unless-stopped
    volumes:
      - ./ephemeral-environments-api:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
      - ./vertuoza-compose:/vertuoza-compose
    environment:
      - PORT=4000
      - NODE_ENV=development
      - TAILSCALE_DOMAIN=${TAILSCALE_DOMAIN:-tailf31c84.ts.net}
      - TAILSCALE_CLIENT_ID=${TAILSCALE_CLIENT_ID}
      - TAILSCALE_CLIENT_SECRET=${TAILSCALE_CLIENT_SECRET}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE:-ephemeral_environments}
      - MYSQL_USER=${MYSQL_USER:-prenvuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-prenvpassword}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - VERTUOZA_COMPOSE_DIR=/vertuoza-compose
      # Google Cloud Authentication
      - GOOGLE_CLOUD_KEYFILE=${GOOGLE_CLOUD_KEYFILE}
      # GitHub Authentication
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "4000:4000"
    networks:
      - ephemeral-environments-network
    depends_on:
      tailscale:
        condition: service_started
      mysql:
        condition: service_healthy

  ephemeral-environments-frontend:
    build:
      context: ./ephemeral-environments-frontend
      dockerfile: Dockerfile
    container_name: ephemeral-environments-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - ephemeral-environments-network
    depends_on:
      - ephemeral-environments-api

networks:
  ephemeral-environments-network:
    name: "ephemeral-environments-network"
    attachable: true

volumes:
  ephemeral-environments-ts-state:
    driver: local
  ephemeral-environments-mysql-data:
    driver: local
