name: 'PR Environment Remove'
description: 'Remove PR environments using the PR Environment API'
author: 'Vertuoza'

inputs:
  repository_name:
    description: 'Name of the repository'
    required: true
  pr_number:
    description: 'PR number'
    required: true
  github_token:
    description: 'GitHub token for commenting on PRs'
    required: true
  api_url:
    description: 'URL of the PR Environment API'
    required: false
    default: 'https://pr-env-api.tailf31c84.ts.net'
  tailscale_domain:
    description: 'Tailscale domain for the PR environment'
    required: false
    default: 'tailf31c84.ts.net'

outputs:
  environment_id:
    description: 'ID of the PR environment'
    value: ${{ steps.set-id.outputs.id }}

runs:
  using: 'composite'
  steps:
    - name: Set environment ID
      id: set-id
      shell: bash
      run: |
        echo "id=${{ inputs.repository_name }}-pr-${{ inputs.pr_number }}" >> $GITHUB_OUTPUT

    - name: Connect to Tailscale
      uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{ secrets.TAILSCALE_CLIENT_ID }}
        oauth-secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
        tags: tag:github-actions

    - name: Remove PR environment
      shell: bash
      run: |
        curl --max-time 600 -X DELETE "${{ inputs.api_url }}/api/environments/${{ steps.set-id.outputs.id }}"

    - name: Comment on PR about removal
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          github.rest.issues.createComment({
            issue_number: ${{ inputs.pr_number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🧹 PR environment has been removed.`
          });
