name: 'Ephemeral Environment Remove'
description: 'Remove ephemeral environments using the Ephemeral Environments API'
author: 'Vertuoza'

inputs:
  repository_name:
    description: 'Name of the repository'
    required: true
  pr_number:
    description: 'PR number'
    required: true
  github_token:
    description: 'GitHub token for commenting on PRs'
    required: true
  tailscale_client_id:
    description: 'Tailscale OAuth client ID'
    required: true
  tailscale_client_secret:
    description: 'Tailscale OAuth client secret'
    required: true
  api_url:
    description: 'URL of the Ephemeral Environments API'
    required: false
    default: 'https://ephemeral-environments-api.tailf31c84.ts.net'
  tailscale_domain:
    description: 'Tailscale domain for the ephemeral environment'
    required: false
    default: 'tailf31c84.ts.net'

outputs:
  environment_id:
    description: 'ID of the PR environment'
    value: ${{ steps.set-id.outputs.id }}

runs:
  using: 'composite'
  steps:
    - name: Set environment ID
      id: set-id
      shell: bash
      run: |
        echo "id=${{ inputs.repository_name }}-pr-${{ inputs.pr_number }}" >> $GITHUB_OUTPUT

    - name: Set up Tailscale
      uses: tailscale/github-action@v3
      with:
        oauth-client-id: ${{ inputs.tailscale_client_id }}
        oauth-secret: ${{ inputs.tailscale_client_secret }}
        tags: tag:ci

    - name: Wait for Tailscale to connect
      run: sleep 10  # Give Tailscale a moment to establish connection

    - name: Remove PR environment
      shell: bash
      run: |
        curl --max-time 600 -X DELETE "${{ inputs.api_url }}/api/environments/${{ steps.set-id.outputs.id }}"

    - name: Comment on PR about removal
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          github.rest.issues.createComment({
            issue_number: ${{ inputs.pr_number }},
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🧹 Ephemeral environment has been removed.`
          });
