name: PR Environment (Simple)

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  # Build service image
  build-service:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push service image
        uses: docker/build-push-action@v4
        with:
          context: .  # Adjust this path to where your Dockerfile is located
          push: true
          tags: ghcr.io/vertuoza/${{ github.repository.name }}:pr-${{ github.event.pull_request.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Create/Update PR environment
  create-update-environment:
    needs: [build-service]
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Create/Update PR Environment
        uses: vertuoza/github-actions/pr-environment-create@main
        with:
          repository_name: ${{ github.repository.name }}
          pr_number: ${{ github.event.pull_request.number }}
          services_json: |
            [
              {
                "name": "${{ github.repository.name }}",
                "image_url": "ghcr.io/vertuoza/${{ github.repository.name }}:pr-${{ github.event.pull_request.number }}"
              }
            ]
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tailscale_client_id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          tailscale_client_secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}

  # Remove PR environment
  remove-environment:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Remove PR Environment
        uses: vertuoza/github-actions/pr-environment-remove@main
        with:
          repository_name: ${{ github.repository.name }}
          pr_number: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tailscale_client_id: ${{ secrets.TAILSCALE_CLIENT_ID }}
          tailscale_client_secret: ${{ secrets.TAILSCALE_CLIENT_SECRET }}
