services:
  ai-php-migrations:
    platform: 'linux/arm64'
    build:
      context: ${VERTUO_BACKEND_PHP_PATH:-../../../vertuo-backend-php}
      dockerfile: packages/services/vertuo-ai/Dockerfile
      target: migrations
