name: PR Environment

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  # Build main service image
  build-main-service:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push main service image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/vertuoza/${{ github.repository.name }}:pr-${{ github.event.pull_request.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Build migrations image
  build-migrations:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push migrations image
        uses: docker/build-push-action@v4
        with:
          context: ./migrations  # Adjust this path to where your migrations Dockerfile is located
          push: true
          tags: ghcr.io/vertuoza/${{ github.repository.name }}-migrations:pr-${{ github.event.pull_request.number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Manage PR environment
  manage-environment:
    needs: [build-main-service, build-migrations]
    if: always()
    runs-on: ubuntu-latest
    steps:
      # For PR opened/updated events
      - name: Create/Update PR Environment
        if: github.event.action != 'closed'
        uses: vertuoza/github-actions/pr-environment-create@main
        with:
          repository_name: ${{ github.repository.name }}
          pr_number: ${{ github.event.pull_request.number }}
          services_json: |
            [
              {
                "name": "${{ github.repository.name }}",
                "image_url": "ghcr.io/vertuoza/${{ github.repository.name }}:pr-${{ github.event.pull_request.number }}"
              },
              {
                "name": "${{ github.repository.name }}-migrations",
                "image_url": "ghcr.io/vertuoza/${{ github.repository.name }}-migrations:pr-${{ github.event.pull_request.number }}"
              }
            ]
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # For PR closed events
      - name: Remove PR Environment
        if: github.event.action == 'closed'
        uses: vertuoza/github-actions/pr-environment-remove@main
        with:
          repository_name: ${{ github.repository.name }}
          pr_number: ${{ github.event.pull_request.number }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
